services:
  db:
    image: mysql:latest
    container_name: products_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - products_db_data:/var/lib/mysql

volumes:
  products_db_data: